version: '3.9'
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/myapp
    # env_file:
    #   - .env
    ports:
      - 8000:8000
    command: sleep infinity
    # depends_on:
    #   - db

  rabbitmq:
    image: rabbitmq:management
    # env_file:
    #   - .env
    # ports:
    #   - "5672:5672"  # AMQP port
    #   - "15672:15672"  # RabbitMQ management console

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A email_service worker -l info
    # environment:
    #   - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    # env_file:
    #   - .env
    volumes:
      - .:/myapp
    depends_on:
      - rabbitmq

